---
title: "ISD analysis"
output: html_notebook
---
```{r setup}
library(replicatebecs)
```

## Fitting GMMs to ISDS

```{r set up GMMS} 
communities <- load_paper_data()

communities_energy <- lapply(communities, add_energy_sizeclass)
isds <- lapply(communities_energy, make_isd)

gmms <- lapply(isds, fit_gmm)
names(gmms) <- names(communities)
```


Assuming ISDs are multimodal (pending figuring out how to a. fit a power law and b. compare fit of power law to best-fitting GMM)...

### Number of modes

```{r nb of modes}
ngaussians <- vapply(gmms, get_ngaussians, FUN.VALUE = 1)
names(ngaussians) <- names(gmms)
ngaussians
```

Note that there can be more modes (Gaussians) than appear in the composite PDF. 

```{r density modes}

pdfs <- lapply(gmms, get_pdf)

modes <- lapply(pdfs, get_modes)

nmodes <- vapply(modes, FUN = length, FUN.VALUE = 4)

modes

nmodes
```


### Placement of modes

```{r stacked pdfs}

all_pdfs <- pdfs[[1]] %>%
  dplyr::mutate(community = names(pdfs)[[1]])

for(i in 2:9) {
  this_pdf <- pdfs[[i]]  %>%
  dplyr::mutate(community = names(pdfs)[[i]])
  
  all_pdfs <- rbind(all_pdfs, this_pdf)
  
  rm(this_pdf)
}

summed_pdfs <- all_pdfs %>%
  dplyr::group_by(sizes) %>%
  dplyr::summarize(density = sum(density)) %>%
  dplyr::mutate(community = "summed")

all_pdfs <- rbind(all_pdfs, summed_pdfs)

summed_pdf_plot <- ggplot2::ggplot(data = all_pdfs, ggplot2::aes(x = sizes, y = density)) + 
                                     ggplot2::scale_x_discrete(limits = c(0, 8)) + 
                                     ggplot2::geom_smooth(stat = "identity", ggplot2::aes(x = all_pdfs$sizes, y = all_pdfs$density, color = all_pdfs$community)) + 
                                     ggplot2::theme_bw()

summed_pdf_plot
                          

```

### Ratio of modes
