---
title: "BSED bootstrapping scenarios"
output: html_notebook
---
```{r setup}
library(replicatebecs)
download_data = FALSE
source_sims = FALSE
storagepath = here::here('files')
set.seed(352) # GNV area code, for fun
```

This is a deeper dive into the outcomes of the BSED analyses using different assumptions in the bootstrapping. 

### Load data and prepare distributions

```{r load data}
if(download_data) download_raw_paper_data()
process_raw_data()
communities <- load_paper_data()
communities_energy <- lapply(communities, FUN = make_community_table, ln_units = 0.2)
bseds <- lapply(communities_energy, FUN = make_bsed)
```

## No energetic constraint

### Uniform size-abundance by .1g (presumed paper approach)

```{r BSED-uniform size abund bootstrapped DOIs, eval = F}

bsed_unif_sizeabund_bootstraps <- lapply(communities, FUN = community_bootstrap,  bootstrap_function = 'bootstrap_unif_sizeabund_bsed_doi', nbootstraps = 10000)

```

```{r source or draw BSED uniform size abund bootstraps}
if(source_sims) {
  load(file.path(storagepath, 'data', 'sims','bsed-options', 'bsed_uniform_bootstraps.Rdata'))
} else {
  
bsed_unif_sizeabund_bootstraps <- lapply(communities, FUN = community_bootstrap,  bootstrap_function = 'bootstrap_unif_sizeabund_bsed_doi', nbootstraps = 10)

save(bsed_unif_sizeabund_bootstraps, file = (file.path(storagepath, 'data', 'sims','bsed-options', 'bsed_uniform_bootstraps.Rdata')))
}
```


```{r plot BSED-uniform bootstrap DOIs v empirical,echo=FALSE, fig.height=10, fig.width=10} 

bsed_unif_sizeabund_bootstrap_plot <- plot_paper_dists(bsed_unif_sizeabund_bootstraps, dist_type = 'bsed_bootstraps')

invisible(bsed_unif_sizeabund_bootstrap_plot)
```

### Uniform size-energy by X units

### Uniform size-abundance by size class

### Uniform size-energy by size class

## Energetically constrained

